spring:
  application:
    name: gateway-service
  cloud:
  
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: SUM-MICROSERVICE
        uri: lb://SUM-MICROSERVICE
        predicates:
        - Path=/sum/**
      - id: RES-MICROSERVICE
        uri: lb://RES-MICROSERVICE
        predicates:
        - Path=/res/**
      - id: DIV-MICROSERVICE
        uri: lb://DIV-MICROSERVICE
        predicates:
        - Path=/div/**
      - id: MTP-MICROSERVICE
        uri: lb://MTP-MICROSERVICE
        predicates:
        - Path=/mtp/**
    discovery:
      enabled: true
      reactive: 
        enabled: false

server:
  port: 3000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  